name: Hello World
on: workflow_dispatch
jobs:
  Built:
    runs-on: ubuntu-latest
    steps:
      - name: Built step
        run: echo "Built stage"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "test stage"
  rele:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: rel step
        run: echo "rele stage"
  prod:
    runs-on: ubuntu-latest
    needs: [ Built, test]
    steps:
      - name: prod step
        run: echo "prod stage"

    
