name: Hello World
on: workflow_dispatch
jobs:
  Built:
    runs-on: ubuntu-latest
    steps:
      - name: Built step
        run: echo "Built stage"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "test stage"

    
