name: Context
on: push
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: context step
        run: |
          echo " the workflow is triggered by ${{github.actor}} "
          echo " the repo name is ${{github.repository}} "
      - name: print all variable on Github
        run: echo " ${{toJson(github)}}
